### ISSUE TITLE
python3 ValueError: can't have unbuffered text I/O

### ISSUE THREAD

**Issue by marev3** [rhempel/ev3dev-lang-python#94] opened 2015-11-21 15:45 UTC
Hi,

I am a beginner in programming with python.
I installed ev3dev-lang-python for python3. When I try to run "motors = [LargeMotor(port) for port in (OUTPUT_B, OUTPUT_C)]" from autodrive.py in demo-folder I get: 
ValueError: can't have unbuffered text I/O

How do I solve this problem?

**Comment by ddemidov** [comment] 2015-11-21 15:46
Should be solved by #93.

**Comment by rhempel** [comment] 2015-11-21 15:47
Which I have not pulled or released yet - please grab the latest from @ddemidov's repo for now - I will be out for the rest of the day

**Comment by ildan95** [comment] 2015-12-27 13:26
Is it solved now? I have this problem yet.

**Comment by ddemidov** [comment] 2015-12-27 13:29
[The fix](https://github.com/rhempel/ev3dev-lang-python/blob/212a249951e2674919a3ce87ca57a1aac8745297/ev3dev/core.py#L81-L91) has been committed to the master branch, but has not been tagged and released yet. So you should use the git version for now.

**Comment by ildan95** [comment] 2015-12-27 20:15
Thanks. It work now. But when I try to run example code:
"from ev3dev import ev3
m = ev3.LargeMotor('outB')
print(m.connected)
m.run_timed(time_sp=3000, duty_cycle_sp=75)"
it always return, that motor wasn't connect and return this error:
"AttributeError: 'LargeMotor' object has no attribute '_path'"

**Comment by ddemidov** [comment] 2015-12-27 20:24
can you please show the output of the following shell command?
```sh
$ cat /sys/class/tacho-motor/*/port_name
```

**Comment by ddemidov** [comment] 2015-12-27 20:27
While I was making the above edit, I realized that the problem could be that you have outdated kernel. So what is the output of
```
uname -a
```
on your ev3?

**Comment by ildan95** [comment] 2015-12-27 21:19
uname -a:
Linux ev3dev 3.16.7-ckt16-7-ev3dev-ev3 #1 PREEMPT Sun Sep 6 22:59:18 CDT 2015 armv5tejl GNU/Linux

"$ cat /sys/class/tacho-motor/*/address" don't work. 
"$ cat /sys/class/tacho-motor/*/port_name" returns:
outC
outB

**Comment by ddemidov** [comment] 2015-12-28 11:24
You need to upgrade your kernel (http://oper.ru/news/read.php?t=1051616561).


`apt-get update && apt-get upgrade && apt-get dist-upgrade` should do it.

**Comment by WasabiFan** [comment] 2015-12-28 14:03
Note that upgrading will make your EV3 incompatible with the current documentation (it has not been updated yet). If you do upgrade, make sure that you understand that other software which uses EV3 motors, sensors, etc. and was written before the new kernel was released will no longer function due to breaking changes. If you don't think you are experienced enough to diverge from the docs for now, wait until we release an image and update the docs.

**Comment by pkshiu** [comment] 2015-12-28 14:51
You can try to get around it by specifying the port_name argument in kwargs. instead of using LargeMotor('outB'), use LargeMotor(port_name='outB')

**Comment by ddemidov** [comment] 2015-12-28 14:57
> You can try to get around it by specifying the port_name argument in kwargs. instead of using LargeMotor('outB'), use LargeMotor(port_name='outB')

That's a nice idea! Another option could be checking out this commit: https://github.com/rhempel/ev3dev-lang-python/commit/ec8b643037902bbda3afc4dcfc7dbb9827afea7b. It has python3 fix merged in, but still uses `port_name` instead of address.

**Comment by rhempel** [comment] 2016-01-02 23:09
@marev3 - please review the status of this defect. If it's solved by upgrading to the new kernel then close.

Also, please consider reviewing the latest README.rst page [here](https://github.com/rhempel/ev3dev-lang-python/blob/update-readme-content/README.rst) to see if this helps you get ev3dev-lang-python working under Python3.

**Comment by marev3** [comment] 2016-01-03 13:39
The original problem described above has been solved as it seems.
But I can't test the whole autodrive.py from the demo folder because at this moment I am working on another robot.

**Comment by marev3** [comment] 2016-01-03 13:44
Okay, I did the following an got an error. I quit with Ctrl + D

robot@ev3dev:~$ python3
Python 3.4.2 (default, Oct  8 2014, 14:47:30) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ev3dev.auto import *
>>> motors = [LargeMotor(address) for address in (OUTPUT_B, OUTPUT_C)]
>>> 
Exception ignored in: <bound method LargeMotor.__del__ of <ev3dev.core.LargeMotor object at 0xb6943650>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 281, in __del__
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 730, in stop
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 295, in command
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 216, in set_attr_string
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 204, in _set_attribute
AttributeError: 'LargeMotor' object has no attribute '_path'
Exception ignored in: <bound method LargeMotor.__del__ of <ev3dev.core.LargeMotor object at 0xb6943b30>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 281, in __del__
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 730, in stop
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 295, in command
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 216, in set_attr_string
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 204, in _set_attribute
AttributeError: 'LargeMotor' object has no attribute '_path'

**Comment by ddemidov** [comment] 2016-01-03 13:59
Do you actually have two large motors connected to ports B and C? What does the following shell command give you?
```sh
$ cat /sys/class/tacho-motor/*/address
```

**Comment by marev3** [comment] 2016-01-03 14:40
robot@ev3dev:~$ cat /sys/class/tacho-motor/*/address
outC
outB
outA

The error message than quitting python3 with Ctrl + D changed slightly:

robot@ev3dev:~$ python3
Python 3.4.2 (default, Oct  8 2014, 14:47:30) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ev3dev.auto import *
>>> motors = [LargeMotor(address) for address in (OUTPUT_B, OUTPUT_C)]
>>> 
Exception ignored in: <bound method LargeMotor.__del__ of <ev3dev.core.LargeMotor object at 0xb69c4650>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 281, in __del__
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 730, in stop
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 295, in command
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 216, in set_attr_string
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 204, in _set_attribute
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 88, in write
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 74, in file_handle
NameError: name 'open' is not defined
Exception ignored in: <bound method LargeMotor.__del__ of <ev3dev.core.LargeMotor object at 0xb69c4ad0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 281, in __del__
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 730, in stop
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 295, in command
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 216, in set_attr_string
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 204, in _set_attribute
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 88, in write
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0.post6-py3.4.egg/ev3dev/core.py", line 74, in file_handle
NameError: name 'open' is not defined

BTW I am using the latest build of ev3dev.

**Comment by ddemidov** [comment] 2016-01-03 14:43
Looks like duplicate of #96

**Comment by dwalton76** [comment] 2016-09-14 03:16
Closing since this is a dup

**Closed by dwalton76** 2016-09-14 03:16 UTC
