### ISSUE TITLE
Python3 Compatibility vs abandoning Python2 Compatibility

### ISSUE THREAD

**Issue by rhempel** [rhempel/ev3dev-lang-python#172] opened 2016-06-05 13:59 UTC
I am not a Python expert, so I'm going to solicit other opinions on this topic.

In the course of fixing up some other defects in the motor drivers and the Python bindings, and in adding unit tests for other EV3 sub-systems, I have had to use Python3 features and libraries in some scripts.

Besides the slower startup time, there are other minor, yet possibly incompatible differences from Python2 that may make force us to to go with one language version over the other. Strings are unicode in Python3 vs raw bytes in Python2, for example.

Can anyone thing of good reasons to stick with both Python2 and Python3 compatibility for the bindings, or are we better off moving to Python3 and abandoning Python2?

**Comment by dlech** [comment] 2016-06-05 14:42
I'm no python expert either, but I know that Debian has a plan to phase out python2 in the next 5 years or so. It will still be in stretch (currently unstable) but probably won't be in buster (stretch + 1). I'm all for python3 only.

**Comment by rhempel** [comment] 2016-06-05 16:45
I was leaning that way but wanted to collect some opinions :-) I'll wait a bit longer while I fix up the testing framework and fix a few binding bugs for more comments.

**Comment by ensonic** [comment] 2016-06-05 18:20
+1 one for python3, but I'd make this an explicit goal and not a side effect of some commit. We definitely want to make sure that all the new example actually work with python3.

**Comment by rhempel** [comment] 2016-06-05 20:24
You were the main opinion I was looking for :-) Stay tuned

**Comment by WasabiFan** [comment] 2016-09-03 04:42
This change has been made, correct? If so, can this be closed?

**Comment by dwalton76** [comment] 2016-09-15 01:40
yep python3 is now enforced
```
robot@ev3dev[lego_official_projects]# ./EV3D4WebControl 
Traceback (most recent call last):
  File "./EV3D4WebControl", line 3, in <module>
    from EV3D4 import EV3D4WebControlled
  File "/home/robot/ev3dev-lang-python/demo/lego_official_projects/EV3D4.py", line 5, in <module>
    from ev3dev.auto import OUTPUT_A, OUTPUT_B, OUTPUT_C, OUTPUT_D
  File "build/bdist.linux-armv5tejl/egg/ev3dev/auto.py", line 21, in <module>
  File "build/bdist.linux-armv5tejl/egg/ev3dev/ev3.py", line 29, in <module>
  File "build/bdist.linux-armv5tejl/egg/ev3dev/core.py", line 36, in <module>
SystemError: Must be using Python 3.4 or higher
robot@ev3dev[lego_official_projects]# 
```

closing this one

**Closed by dwalton76** 2016-09-15 01:40 UTC

**Comment by ensonic** [comment] 2016-09-27 13:02
I have updated my image yesterday:
> python --version
Python 2.7.9
> python3 --version
Python 3.4.2
> apt-cache show python-ev3dev | grep -i version
Version: 0.6.0

at this point I need some help how to figure out what I need to change. Also isn't 0.6.0 the old version still:
https://github.com/rhempel/ev3dev-lang-python/releases/tag/0.6.0

**Comment by ddemidov** [comment] 2016-09-27 13:10
`apt-cache show python3-ev3dev | grep -i version` should show `0.7.0-rc1`. Version 0.7.0 is not yet tagged, so I understand @dlech published its prerelease based on some of the latest commits in develop.

Latest version of the library that is compatible with python2 is 0.6.0, but the problem is that this version is no longer works with the latest kernels. So you would have to switch openroberta to python3, if possible, or complain in #219 so that we keep python2 compatibility otherwise. Both options would still require you to update the part of your scripts that works with motors.

Related: ev3dev/ev3dev#749, http://www.ev3dev.org/news/2016/04/11/Kernel-Release-Cycle-10/

**Comment by ensonic** [comment] 2016-09-28 14:35
I've ported the code to python3. Main issues: 
* there is no python3-bluez (workaround applied)
* #126
The other things seem to work.

**Comment by ddemidov** [comment] 2016-09-28 14:43
I think I've just fixed #126.

**Comment by fferri** [comment] 2017-04-23 12:58
One reason to maintain Python 2.7 compatibility is to be compatible with ROS, a middleware for distributed robotic applications (e.g. one part of your program runs on the EV3, another part runs on a laptop computer... and there is a huge stack of software components with state of the art algorithms for AI and Robotics)

**Comment by ensonic** [comment] 2017-04-23 16:23
ROS is moving towards python 3.X as well.
http://wiki.ros.org/python_2_and_3_compatible_code

**Comment by fferri** [comment] 2017-04-24 17:20
currently there are no ros packages for python3
