### ISSUE TITLE
Add sample code to documentation

### ISSUE THREAD

**Issue by bittner** [rhempel/ev3dev-lang-python#104] opened 2016-01-01 20:37 UTC
The [current documentation](http://python-ev3dev.readthedocs.org/en/latest/) may need some sample code to get started. The [sample code](http://ddemidov.github.io/ev3dev-lang-python/#usage) from the old documentation is nice, but unsurprisingly it's now broken.

**Comment by ddemidov** [comment] 2016-01-01 21:03
Just a note: there are a couple of demos in the new repo as well: https://github.com/rhempel/ev3dev-lang-python/tree/master/demo

**Comment by ddemidov** [comment] 2016-01-01 21:05
Another note to @rhempel: the sample code from the old repo was copied from README. Same thing will happen if you update the README here. Fell free to reuse my old one.

**Comment by bittner** [comment] 2016-01-01 21:41
This may be a duplicate of #47.

**Comment by rhempel** [comment] 2016-01-02 23:06
It is a duplicate of #47. But I'd appreciate separate review anyways.

Please review a43897fe0d380a6449b4dcd1c691be551056b3dd to see if this fixes the issue. I have added links to "Demo Robot" and "Demo Code" in the docs - this will be part of ReadTheDocs as well after the next release.

The resulting GitHub README.rst page [is here](https://github.com/rhempel/ev3dev-lang-python/blob/update-readme-content/README.rst)

**Comment by bittner** [comment] 2016-01-03 22:46
I've noticed that the current documentation is the one generated from the docstrings. That's good, though a sweet introduction presenting the separate features of the API would probably be easier to digest. I'm thinking of maybe a thinking-aloud walk through of the [demo modules I propose](https://github.com/rhempel/ev3dev-lang-python/commit/a43897fe0d380a6449b4dcd1c691be551056b3dd#commitcomment-15235513).

The wording could be generic enough so that those chapters of the docs will rarely have to be touched. As soon as the demos exist how to write those chapters may become more obvious. The indeed nice [Example Code](https://github.com/rhempel/ev3dev-lang-python/blob/update-readme-content/README.rst#example-code) section of the README could then be replaced by a link to the documentation.

**Comment by rhempel** [comment] 2016-01-03 23:01
Well, this is a bit of a problem (or an opportunity if you're inclined that way) - I agree that a nice tutorial would be a good thing. We do, however, plan to add bindings for at least Lua and Ruby (and maybe Lisp) in the future.

Where I am going with this is that I'd hate to write an API tutorial for Python and have to do the same thing all over again for each language.

I think we are talking about is more of a "How to Program a Robot Using the ev3dev Device API in ANY Language" type of text ...

**Comment by WasabiFan** [comment] 2016-01-03 23:25
> We do, however, plan to add bindings for at least Lua and Ruby (and maybe Lisp) in the future.

Don't forget the other ones that already exist but haven't been integrated -- we have PRs/issues open for C# and Java! And we had a conversation yesterday with someone working on Go.

**Comment by bittner** [comment] 2016-01-03 23:27
That's cool, and I agree.
We just need to make sure that failure doesn't start with the very first import statement:
``` python
import ev3dev.ev3 as ev3

# or, alternatively
from ev3dev.ev3 import *
```
... is not *totally* obvious, and not *the* standard way of using a module. I've seen the need for it though, looking at the `auto` module. The "obvious way", I feel, would be that
``` python
from ev3dev import *
```
would do just the same as the alternative import example above. (Relates to #105)

Either this way, or if in all other languages importing does require the very same "non-standard" procedure an abstract tutorial for all languages will of course do it.

**Comment by rhempel** [comment] 2016-01-04 01:10
Believe me, we went around in circles for the best way to do this given all of the different hardware to support. The examples make it clear how to do the first import - let's stick with it for now and move on :-)

**Closed** 2016-01-05 23:36 UTC

**Comment by bittner** [comment] 2016-01-07 13:22
Would you accept a PR that moves the [Example Code](https://github.com/rhempel/ev3dev-lang-python/blob/update-readme-content/README.rst#example-code) section of the README into a set of demo modules, and refactor the `demo` directory structure [as described above](#issuecomment-168549093)?

**Comment by rhempel** [comment] 2016-01-07 17:44
Sure, I'm happy to review such a PR - I think what you are saying is that the DemoCode from the current README goes to a separate document.

Recall that the README gets used in two places - as the descriptive header in the REPO, and in the more complete docs in ReadTheDocs.

Ideally, I'd like to see the API set up with general text - as each language binding must provide the text and we can describe the *operation* of the file based attributes very well. Then autogen the code examples and language specific tips and tricks separately.

But let's see what you are proposing - either way the effort won't go to waste because we can pull out the text to be re-used if we ever refactor the docs.
